version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: '00:00'
    commit-message:
      prefix: chore
      include: scope
    versioning-strategy: "widen"
    reviewers:
      - "AntoineLelaisant"
